### ISSUE TITLE
Cannot use router context from Drawer component

### ISSUE THREAD

**Issue by jcasanova** [react-toolbox/react-toolbox#304]
Trying to build a navigation `Drawer` as main nav.
Actually it seems like the `Overlay` (used by `Drawer`) component writes its children out of the regular flow. Thus preventing any component to access parent router history context.

I reviewed react-toolbox documentation but as far as I can see, its navigation component does not use the `Drawer` component.

Am I missing something?

**Comment by javivelasco** [comment]
Yes, I think this can be fixed. The `Drawer` component should be rendered with an Overlay so it takes place out of the tree. In the documentation is not used because it's a fixed navigation and this is not implemented yet. Maybe we should try to render a fixed node under the root component and render the drawer there so it can access the history? Not sure, I have to dig deeper

**Comment by jcasanova** [comment]
@javivelasco why do you need a specific rendering for the `Overlay`?
I actually created my main `Drawer` and `Overlay` components, mainly copying react-toolbox code, and the `Overlay` renders in the flow ... working like a charm

```javascript
import React from 'react'
import ClassNames from 'classnames'
import style from './style'

const Overlay = (props) => {
  const className = ClassNames(style.root, {
    [style.active]: props.active,
    [style.invisible]: props.invisible
  }, props.className)

  return (
    <div className={className}>
      <div className={style.overlay} onClick={props.onClick} />
      {props.children}
    </div>
  )
}

Overlay.propTypes = {
  active: React.PropTypes.bool,
  children: React.PropTypes.node,
  className: React.PropTypes.string,
  invisible: React.PropTypes.bool,
  onClick: React.PropTypes.func
}

Overlay.defaultProps = {
  invisible: false
}

export default Overlay
```

**Comment by kagux** [comment]
I've answered a very similar question yesterday in this PR https://github.com/react-toolbox/react-toolbox/pull/311
While this implementation of overlay works fine for your use case, there are edge cases you're not accounting for. Try the docs site with your overlay.

**Comment by javivelasco** [comment]
It's just because the overlay takes the whole viewport. If a parent node uses transform properties then the overlay cannot take the whole viewport. You can try modifying the `Overlay` component and using if in the docs project as @kagux says. 

As I said in #311 the best would be to render the `Overlay` inside the component tree but in the top element so no parent node can take effect over it/

**Comment by jcasanova** [comment]
ok thanks @kagux @javivelasco for your explanations.
Would we need to always render an `Overlay` as first child of the root component, then use a ref to this component whenever another component such as `Drawer` or `Dialog` needs it? Is this possible with React?

**Comment by patrick-jones** [comment]
This would  fixed by #313, which is awaiting review. I basically did what @javivelasco mentions -- the scrim is within the tree, under the main Layout component.

**Comment by emirotin** [comment]
Is my problem related?
I use redux and react-redux

When I place my _connected_ component inside of the Drawer I get `Could not find "store" in either the context or props of "Connect(SidebarHeader)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(SidebarHeader)"` (whre `SidebarHeader` is the name of my component class).

**Comment by patrick-jones** [comment]
@emirotin Yes, because the redux-react `Provider` places the store on the context, which is passed down through the tree.

**Comment by emirotin** [comment]
I managed to partially work it around by passing the `store` down the components chain (which is ugly, but works somehow). But it's still not the universal solution.

For example, react-router's Link does `this.context.router.push(_location);` which fails, and it's a 3rd party component, so I cannot alter its context.

**Comment by javivelasco** [comment]
Guys gonna review it this afternoon/night. I'm very busy this days, sorry for the delay :(

**Comment by emirotin** [comment]
That's understandable, np
I'm going to experiment with re-creating the Provider inside of the Drawer
as a universal work-around. But still obviously it will be much nicer for
things to render in the predictable place of the tree.

**Comment by javivelasco** [comment]
Sure thing, I'm going to do some experiments during the weekend too. This is important

**Comment by javivelasco** [comment]
Check the commit. This is an unstable feature, `unstable_renderSubtreeIntoContainer` works in a similar way that `render` does but it accepts a context as a first parameter so it can pass the context by and make routes and stores accesible from child components.

**Comment by emirotin** [comment]
Thanks. For now we've managed to forward the context ourselves, but would be nice to remove that code. How badly unstable is it?

**Comment by javivelasco** [comment]
Not sure, I hope it will be considered stable for the next release... IMO it's a very important feature

**Comment by emirotin** [comment]
Thanks.

**Comment by emirotin** [comment]
Tested, seems to be OK
